export const followersData = [
  { id:'FOL-001', follower:'Marcus Chen',   uid:'UID-7823', provider:'Rehan Capital', strategy:'Apex Scalper Pro',    alloc:'$5,000', ratio:'1:1',  status:'ACTIVE', pnl:'+$312',  pnlN:312,  risk:'LOW',  lastActivity:'2 min ago', copyRatio:'1.0x', maxDD:'5%' },
  { id:'FOL-002', follower:'Priya Mehta',   uid:'UID-3341', provider:'Apex Markets',   strategy:'Gold Trend Master',   alloc:'$2,500', ratio:'0.5:1',status:'ACTIVE', pnl:'-$48',   pnlN:-48,  risk:'LOW',  lastActivity:'14 min ago',copyRatio:'0.5x', maxDD:'5%' },
  { id:'FOL-003', follower:'Dev Patel',     uid:'UID-6634', provider:'Rehan Capital', strategy:'Apex Scalper Pro',    alloc:'$10,000',ratio:'2:1',  status:'ACTIVE', pnl:'+$1,204',pnlN:1204, risk:'MED',  lastActivity:'1h ago',    copyRatio:'2.0x', maxDD:'8%' },
  { id:'FOL-004', follower:'Lena Schmidt',  uid:'UID-5588', provider:'FinEdge Global', strategy:'FinEdge Multi-Asset', alloc:'$1,000', ratio:'0.25:1',status:'PAUSED', pnl:'+$67',   pnlN:67,   risk:'LOW',  lastActivity:'3h ago',    copyRatio:'0.25x',maxDD:'5%' },
  { id:'FOL-005', follower:'Ali Hassan',    uid:'UID-9102', provider:'TradeBridge SG', strategy:'Bridge Momentum FX',  alloc:'$15,000',ratio:'3:1',  status:'ACTIVE', pnl:'-$820',  pnlN:-820, risk:'HIGH', lastActivity:'5h ago',    copyRatio:'3.0x', maxDD:'10%' },
  { id:'FOL-006', follower:'Yuki Tanaka',   uid:'UID-1182', provider:'Euro IB Net',    strategy:'Euro Steady Growth',  alloc:'$3,000', ratio:'1:1',  status:'ACTIVE', pnl:'+$184',  pnlN:184,  risk:'LOW',  lastActivity:'2h ago',    copyRatio:'1.0x', maxDD:'5%' },
  { id:'FOL-007', follower:'Nina Voronova', uid:'UID-2298', provider:'Nile Trading EG',strategy:'Nile FX Aggressive',  alloc:'$500',   ratio:'0.5:1',status:'PAUSED', pnl:'-$92',   pnlN:-92,  risk:'HIGH', lastActivity:'1d ago',    copyRatio:'0.5x', maxDD:'15%' },
  { id:'FOL-008', follower:'Kwame Asante',  uid:'UID-4421', provider:'Apex Markets',   strategy:'Gold Trend Master',   alloc:'$8,000', ratio:'1.5:1',status:'ACTIVE', pnl:'+$640',  pnlN:640,  risk:'MED',  lastActivity:'3h ago',    copyRatio:'1.5x', maxDD:'8%' },
  { id:'FOL-009', follower:'Ivan Petrov',   uid:'UID-7710', provider:'Rehan Capital', strategy:'Apex Scalper Pro',    alloc:'$20,000',ratio:'2:1',  status:'ACTIVE', pnl:'+$2,480',pnlN:2480, risk:'HIGH', lastActivity:'30 min ago',copyRatio:'2.0x', maxDD:'10%' },
  { id:'FOL-010', follower:'Sam Torres',    uid:'UID-8821', provider:'Pacific Refs',   strategy:'Pacific Carry Trade', alloc:'$4,000', ratio:'1:1',  status:'PAUSED', pnl:'-$118',  pnlN:-118, risk:'MED',  lastActivity:'6h ago',    copyRatio:'1.0x', maxDD:'8%' },
];
