export const providersData = [
  { id:'IB-001', name:'Rehan Capital',   region:'UAE', strategies:4,  followers:4210, aum:'$3.84M', winRate:'66.2%', winRateN:66.2, drawdown:'-3.8%', ddN:3.8,  approval:'APPROVED', status:'ACTIVE',    verified:true,  risk:'LOW',  rating:4.9, email:'rehan@rc.com',    kyc:'VERIFIED', joined:'2023-01-10' },
  { id:'IB-002', name:'Apex Markets',    region:'UK',  strategies:3,  followers:3120, aum:'$2.71M', winRate:'60.4%', winRateN:60.4, drawdown:'-5.1%', ddN:5.1,  approval:'APPROVED', status:'ACTIVE',    verified:true,  risk:'MED',  rating:4.6, email:'ops@apex.uk',     kyc:'VERIFIED', joined:'2023-02-14' },
  { id:'IB-003', name:'FinEdge Global',  region:'IN',  strategies:3,  followers:2480, aum:'$2.02M', winRate:'58.1%', winRateN:58.1, drawdown:'-6.4%', ddN:6.4,  approval:'APPROVED', status:'ACTIVE',    verified:true,  risk:'MED',  rating:4.4, email:'fin@finedge.in',  kyc:'VERIFIED', joined:'2023-03-08' },
  { id:'IB-004', name:'TradeBridge SG',  region:'SG',  strategies:2,  followers:1820, aum:'$1.64M', winRate:'53.8%', winRateN:53.8, drawdown:'-8.4%', ddN:8.4,  approval:'APPROVED', status:'ACTIVE',    verified:true,  risk:'HIGH', rating:4.1, email:'sg@tradebridge.com',kyc:'VERIFIED', joined:'2023-04-21' },
  { id:'IB-005', name:'Euro IB Net',     region:'DE',  strategies:2,  followers:1240, aum:'$1.12M', winRate:'61.8%', winRateN:61.8, drawdown:'-4.2%', ddN:4.2,  approval:'APPROVED', status:'ACTIVE',    verified:true,  risk:'LOW',  rating:4.3, email:'euro@euroib.de',  kyc:'VERIFIED', joined:'2023-05-15' },
  { id:'IB-006', name:'Nile Trading EG', region:'EG',  strategies:1,  followers:640,  aum:'$580K',  winRate:'47.4%', winRateN:47.4, drawdown:'-13.8%',ddN:13.8, approval:'REVIEW',   status:'ACTIVE',    verified:false, risk:'HIGH', rating:3.8, email:'nile@nteg.com',   kyc:'PENDING',  joined:'2023-06-30' },
  { id:'IB-007', name:'Pacific Refs',    region:'AU',  strategies:1,  followers:420,  aum:'$380K',  winRate:'55.2%', winRateN:55.2, drawdown:'-7.6%', ddN:7.6,  approval:'APPROVED', status:'ACTIVE',    verified:true,  risk:'MED',  rating:4.0, email:'pac@pacrefs.au',  kyc:'VERIFIED', joined:'2023-07-12' },
  { id:'IB-008', name:'Atlas IB Group',  region:'ZA',  strategies:1,  followers:210,  aum:'$190K',  winRate:'70.4%', winRateN:70.4, drawdown:'-2.4%', ddN:2.4,  approval:'PENDING',  status:'SUSPENDED', verified:false, risk:'LOW',  rating:3.2, email:'atlas@atlasib.za',kyc:'REVIEW',   joined:'2024-01-15' },
];
