export const statusVariantMap = {
  active: 'success',
  verified: 'success',
  approved: 'success',
  approve: 'success',
  completed: 'success',
  connected: 'success',
  funded: 'success',
  settled: 'success',
  success: 'success',
  healthy: 'success',
  top: 'success',
  ready: 'success',
  received: 'success',
  open: 'info',
  live: 'info',
  info: 'info',
  low: 'info',
  gold: 'info',
  elite: 'info',
  global: 'info',
  finance: 'info',
  users: 'info',
  trading: 'info',
  audit: 'info',
  infra: 'info',
  api: 'info',
  csv: 'info',
  xlsx: 'info',
  zip: 'info',
  pending: 'warning',
  review: 'warning',
  'in-review': 'warning',
  paused: 'warning',
  flagged: 'warning',
  warning: 'warning',
  escalated: 'warning',
  medium: 'warning',
  watch: 'warning',
  'watchlist': 'warning',
  'in-progress': 'warning',
  'new-device': 'warning',
  processing: 'warning',
  review_only: 'warning',
  platinum: 'warning',
  desk: 'warning',
  challenge: 'warning',
  funded_scope: 'warning',
  trial: 'warning',
  failed: 'danger',
  rejected: 'danger',
  reject: 'danger',
  blocked: 'danger',
  limited: 'danger',
  disconnected: 'danger',
  critical: 'danger',
  high: 'danger',
  breach: 'danger',
  restricted: 'danger',
  'high-risk': 'danger',
  hold: 'danger',
  draft: 'danger',
  expired: 'danger',
};

export function getStatusVariant(status = '') {
  const normalized = String(status)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return statusVariantMap[normalized] ?? 'muted';
}
