import { matchPath } from 'react-router-dom';
import { PERMISSIONS } from '../config/permissions';

export const ROUTE_META = [
  { pattern: '/', title: 'Dashboard Control', section: 'Dashboard', permission: PERMISSIONS.dashboard.view },
  { pattern: '/users', title: 'Master User List', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/users/kyc', title: 'KYC Requests', section: 'Users', permission: PERMISSIONS.users.kyc },
  { pattern: '/users/mt5', title: 'MT5 Accounts', section: 'Users', permission: PERMISSIONS.users.mt5 },
  { pattern: '/users/:userId', title: 'User Overview', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/users/:userId/overview', title: 'User Overview', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/users/:userId/profile', title: 'User Profile', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/users/:userId/kyc', title: 'User details', section: 'Users', permission: PERMISSIONS.users.kyc },
  { pattern: '/users/:userId/wallet', title: 'User Wallet', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/users/:userId/mt5-accounts', title: 'User MT5 Accounts', section: 'Users', permission: PERMISSIONS.users.mt5 },
  { pattern: '/users/:userId/trading-history', title: 'User Trading History', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/users/:userId/activity-logs', title: 'User Activity Logs', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/users/:userId/risk-view', title: 'User Risk View', section: 'Users', permission: PERMISSIONS.users.risk },
  { pattern: '/users/:userId/notes', title: 'User Notes', section: 'Users', permission: PERMISSIONS.users.view },
  { pattern: '/finance/deposits', title: 'Deposit Ledger', section: 'Finance', permission: PERMISSIONS.finance.view },
  { pattern: '/finance/withdrawals', title: 'Withdrawal Approvals', section: 'Finance', permission: PERMISSIONS.finance.view },
  { pattern: '/finance/transactions', title: 'Transaction Stream', section: 'Finance', permission: PERMISSIONS.finance.view },
  { pattern: '/finance/failed-payments', title: 'Failed Payments', section: 'Finance', permission: PERMISSIONS.finance.view },
  { pattern: '/finance/approvals', title: 'Manual Approvals', section: 'Finance', permission: PERMISSIONS.finance.approve },
  { pattern: '/finance/:slug/:id', title: 'Finance  Details', section: 'Finance', permission: PERMISSIONS.finance.view },
  { pattern: '/trading/accounts', title: 'Trading Accounts', section: 'Trading', permission: PERMISSIONS.trading.view },
  { pattern: '/trading/orders', title: 'Orders Monitor', section: 'Trading', permission: PERMISSIONS.trading.view },
  { pattern: '/trading/positions', title: 'Live Positions', section: 'Trading', permission: PERMISSIONS.trading.view },
  { pattern: '/trading/history', title: 'Trade History', section: 'Trading', permission: PERMISSIONS.trading.view },
  { pattern: '/trading/execution-logs', title: 'Execution Logs', section: 'Trading', permission: PERMISSIONS.trading.view },
  { pattern: '/copy-trading/strategies', title: 'Copy Strategies', section: 'Copy-Trading', permission: PERMISSIONS.copyTrading.view },
  { pattern: '/copy-trading/providers', title: 'Copy Providers', section: 'Copy-Trading', permission: PERMISSIONS.copyTrading.view },
  { pattern: '/copy-trading/followers', title: 'Copy Followers', section: 'Copy-Trading', permission: PERMISSIONS.copyTrading.view },
  { pattern: '/copy-trading/subscriptions', title: 'Copy Subscriptions', section: 'Copy-Trading', permission: PERMISSIONS.copyTrading.view },
  { pattern: '/copy-trading/performance', title: 'Copy Performance', section: 'Copy-Trading', permission: PERMISSIONS.copyTrading.view },
  { pattern: '/copy-trading/logs', title: 'Copy Logs', section: 'Copy-Trading', permission: PERMISSIONS.copyTrading.view },
  { pattern: '/prop-trading', title: 'Prop Trading Overview', section: 'Prop-Trading', permission: PERMISSIONS.propTrading.view },
  { pattern: '/prop-trading/challenge-configurations', title: 'Challenge Configurations', section: 'Prop-Trading', permission: PERMISSIONS.propTrading.manage },
  { pattern: '/prop-trading/evaluation-requests', title: 'Evaluation Requests', section: 'Prop-Trading', permission: PERMISSIONS.propTrading.approve },
  { pattern: '/prop-trading/funded-accounts', title: 'Funded Accounts', section: 'Prop-Trading', permission: PERMISSIONS.propTrading.view },
  { pattern: '/prop-trading/statistics', title: 'Challenge Statistics', section: 'Prop-Trading', permission: PERMISSIONS.propTrading.view },
  { pattern: '/prop-trading/fees-coupons', title: 'Fees & Coupons', section: 'Prop-Trading', permission: PERMISSIONS.propTrading.manage },
  { pattern: '/prop-trading/rules-risk', title: 'Rules / Risk Settings', section: 'Prop-Trading', permission: PERMISSIONS.propTrading.manage },
  { pattern: '/ib-system/referrals', title: 'Referral Network', section: 'IB-System', permission: PERMISSIONS.ibSystem.view },
  { pattern: '/ib-system/commissions', title: 'Commission History', section: 'IB-System', permission: PERMISSIONS.ibSystem.view },
  { pattern: '/ib-system/payouts', title: 'IB Payouts', section: 'IB-System', permission: PERMISSIONS.ibSystem.payouts },
  { pattern: '/ib-system/performance', title: 'IB Performance', section: 'IB-System', permission: PERMISSIONS.ibSystem.view },
  { pattern: '/reports/finance', title: 'Finance Reports', section: 'Reports', permission: PERMISSIONS.reports.view },
  { pattern: '/reports/trading', title: 'Trading Reports', section: 'Reports', permission: PERMISSIONS.reports.view },
  { pattern: '/reports/users', title: 'User Reports', section: 'Reports', permission: PERMISSIONS.reports.view },
  { pattern: '/reports/system', title: 'System Reports', section: 'Reports', permission: PERMISSIONS.reports.view },
  { pattern: '/reports/exports', title: 'Export Center', section: 'Reports', permission: PERMISSIONS.reports.export },
  { pattern: '/support/tickets', title: 'Tickets Queue', section: 'Support', permission: PERMISSIONS.support.view },
  { pattern: '/support/tickets/:ticketId', title: 'Ticket Details', section: 'Support', permission: PERMISSIONS.support.view },
  { pattern: '/support/escalated', title: 'Escalated Tickets', section: 'Support', permission: PERMISSIONS.support.escalate },
  { pattern: '/settings/api', title: 'API Configuration', section: 'Settings', permission: PERMISSIONS.settings.view },
  { pattern: '/settings/payment-gateway', title: 'Payment Gateway', section: 'Settings', permission: PERMISSIONS.settings.view },
  { pattern: '/settings/kyc', title: 'KYC Settings', section: 'Settings', permission: PERMISSIONS.settings.view },
  { pattern: '/settings/trading', title: 'Trading Settings', section: 'Settings', permission: PERMISSIONS.settings.view },
  { pattern: '/settings/notifications', title: 'Notification Settings', section: 'Settings', permission: PERMISSIONS.settings.view },
  { pattern: '/settings/system', title: 'System Settings', section: 'Settings', permission: PERMISSIONS.settings.view },
  { pattern: '/admin-mgmt/users', title: 'Admin Users', section: 'Admin', permission: PERMISSIONS.adminMgmt.view },
  { pattern: '/admin-mgmt/roles', title: 'Roles', section: 'Admin', permission: PERMISSIONS.adminMgmt.view },
  { pattern: '/admin-mgmt/permissions', title: 'Permissions Matrix', section: 'Admin', permission: PERMISSIONS.adminMgmt.view },
  { pattern: '/admin-mgmt/access-logs', title: 'Access Logs', section: 'Admin', permission: PERMISSIONS.adminMgmt.view },
  { pattern: '/admin-mgmt/activity-logs', title: 'Activity Logs', section: 'Admin', permission: PERMISSIONS.adminMgmt.view },
];

export function getRouteMeta(pathname) {
  return ROUTE_META.find((route) => matchPath({ path: route.pattern, end: true }, pathname))
    ?? ROUTE_META[0];
}
