import {
  Copy,
  FileText,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Settings,
  Share2,
  ShieldCheck,
  Trophy,
  Users,
  Wallet,
} from 'lucide-react';
import { PERMISSIONS } from './permissions';

export const adminNavigation = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    path: '/',
    permission: PERMISSIONS.dashboard.view,
  },
  {
    id: 'users',
    label: 'User Management',
    icon: Users,
    path: '/users',
    permission: PERMISSIONS.users.view,
    subItems: [
      { id: 'users-list', label: 'User List', path: '/users', permission: PERMISSIONS.users.view },
      { id: 'users-kyc', label: 'KYC Requests', path: '/users/kyc', permission: PERMISSIONS.users.kyc },
      { id: 'users-mt5', label: 'MT5 Accounts', path: '/users/mt5', permission: PERMISSIONS.users.mt5 },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    icon: Wallet,
    path: '/finance/deposits',
    permission: PERMISSIONS.finance.view,
    subItems: [
      { id: 'finance-deposits', label: 'Deposits', path: '/finance/deposits', permission: PERMISSIONS.finance.view },
      { id: 'finance-withdrawals', label: 'Withdrawals', path: '/finance/withdrawals', permission: PERMISSIONS.finance.view },
      { id: 'finance-transactions', label: 'Transactions', path: '/finance/transactions', permission: PERMISSIONS.finance.view },
      { id: 'finance-failed', label: 'Failed Payments', path: '/finance/failed-payments', permission: PERMISSIONS.finance.view },
      { id: 'finance-approvals', label: 'Approvals', path: '/finance/approvals', permission: PERMISSIONS.finance.approve },
    ],
  },
  {
    id: 'trading',
    label: 'Trading Operations',
    icon: LineChart,
    path: '/trading/accounts',
    permission: PERMISSIONS.trading.view,
    subItems: [
      { id: 'trading-accounts', label: 'Trading Accounts', path: '/trading/accounts', permission: PERMISSIONS.trading.view },
      { id: 'trading-orders', label: 'Orders', path: '/trading/orders', permission: PERMISSIONS.trading.view },
      { id: 'trading-positions', label: 'Positions', path: '/trading/positions', permission: PERMISSIONS.trading.view },
      { id: 'trading-history', label: 'Trade History', path: '/trading/history', permission: PERMISSIONS.trading.view },
      { id: 'trading-logs', label: 'Execution Logs', path: '/trading/execution-logs', permission: PERMISSIONS.trading.view },
    ],
  },
  {
    id: 'copy-trading',
    label: 'Copy Trading',
    icon: Copy,
    path: '/copy-trading/strategies',
    permission: PERMISSIONS.copyTrading.view,
    subItems: [
      { id: 'copy-strategies', label: 'Strategies', path: '/copy-trading/strategies', permission: PERMISSIONS.copyTrading.view },
      { id: 'copy-providers', label: 'Providers', path: '/copy-trading/providers', permission: PERMISSIONS.copyTrading.view },
      { id: 'copy-followers', label: 'Followers', path: '/copy-trading/followers', permission: PERMISSIONS.copyTrading.view },
      { id: 'copy-subscriptions', label: 'Subscriptions', path: '/copy-trading/subscriptions', permission: PERMISSIONS.copyTrading.view },
      { id: 'copy-performance', label: 'Performance', path: '/copy-trading/performance', permission: PERMISSIONS.copyTrading.view },
      { id: 'copy-logs', label: 'Logs', path: '/copy-trading/logs', permission: PERMISSIONS.copyTrading.view },
    ],
  },
  {
    id: 'prop-trading',
    label: 'Prop Trading',
    icon: Trophy,
    path: '/prop-trading',
    permission: PERMISSIONS.propTrading.view,
    subItems: [
      { id: 'prop-overview', label: 'Overview', path: '/prop-trading', permission: PERMISSIONS.propTrading.view },
      { id: 'prop-configs', label: 'Challenge Configurations', path: '/prop-trading/challenge-configurations', permission: PERMISSIONS.propTrading.manage },
      { id: 'prop-evaluations', label: 'Evaluation Requests', path: '/prop-trading/evaluation-requests', permission: PERMISSIONS.propTrading.approve },
      { id: 'prop-funded', label: 'Funded Accounts', path: '/prop-trading/funded-accounts', permission: PERMISSIONS.propTrading.view },
      { id: 'prop-stats', label: 'Statistics', path: '/prop-trading/statistics', permission: PERMISSIONS.propTrading.view },
      { id: 'prop-fees', label: 'Fees & Coupons', path: '/prop-trading/fees-coupons', permission: PERMISSIONS.propTrading.manage },
      { id: 'prop-rules', label: 'Rules / Risk Settings', path: '/prop-trading/rules-risk', permission: PERMISSIONS.propTrading.manage },
    ],
  },
  {
    id: 'ib-system',
    label: 'IB System',
    icon: Share2,
    path: '/ib-system/overview',
    permission: PERMISSIONS.ibSystem.view,
    subItems: [
      { id: 'ib-overview',     label: 'Overview',       path: '/ib-system/overview',     permission: PERMISSIONS.ibSystem.view    },
      { id: 'ib-referrals',   label: 'Referrals',      path: '/ib-system/referrals',    permission: PERMISSIONS.ibSystem.view    },
      { id: 'ib-commissions', label: 'Commissions',    path: '/ib-system/commissions',   permission: PERMISSIONS.ibSystem.view    },
      { id: 'ib-payouts',     label: 'Payouts',        path: '/ib-system/payouts',       permission: PERMISSIONS.ibSystem.payouts },
      { id: 'ib-performance', label: 'IB Performance', path: '/ib-system/performance',   permission: PERMISSIONS.ibSystem.view    },
      { id: 'ib-tree',        label: 'Partner Tree',   path: '/ib-system/tree',          permission: PERMISSIONS.ibSystem.view    },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: FileText,
    path: '/reports/finance',
    permission: PERMISSIONS.reports.view,
    subItems: [
      { id: 'reports-finance', label: 'Finance Reports', path: '/reports/finance', permission: PERMISSIONS.reports.view },
      { id: 'reports-trading', label: 'Trading Reports', path: '/reports/trading', permission: PERMISSIONS.reports.view },
      { id: 'reports-users', label: 'User Reports', path: '/reports/users', permission: PERMISSIONS.reports.view },
      { id: 'reports-system', label: 'System Reports', path: '/reports/system', permission: PERMISSIONS.reports.view },
      { id: 'reports-exports', label: 'Export Center', path: '/reports/exports', permission: PERMISSIONS.reports.export },
    ],
  },
  {
    id: 'support',
    label: 'Support',
    icon: LifeBuoy,
    path: '/support/tickets',
    permission: PERMISSIONS.support.view,
    subItems: [
      { id: 'support-tickets', label: 'Tickets', path: '/support/tickets', permission: PERMISSIONS.support.view },
      { id: 'support-escalated', label: 'Escalated Tickets', path: '/support/escalated', permission: PERMISSIONS.support.escalate },
    ],
  },
  {
    id: 'settings',
    label: 'Platform Settings',
    icon: Settings,
    path: '/settings/api',
    permission: PERMISSIONS.settings.view,
    subItems: [
      { id: 'settings-api', label: 'API Config', path: '/settings/api', permission: PERMISSIONS.settings.view },
      { id: 'settings-payments', label: 'Payment Gateway', path: '/settings/payment-gateway', permission: PERMISSIONS.settings.view },
      { id: 'settings-kyc', label: 'KYC Settings', path: '/settings/kyc', permission: PERMISSIONS.settings.view },
      { id: 'settings-trading', label: 'Trading Settings', path: '/settings/trading', permission: PERMISSIONS.settings.view },
      { id: 'settings-notifications', label: 'Notification Settings', path: '/settings/notifications', permission: PERMISSIONS.settings.view },
      { id: 'settings-system', label: 'System Settings', path: '/settings/system', permission: PERMISSIONS.settings.view },
    ],
  },
  {
    id: 'admin-mgmt',
    label: 'Admin Management',
    icon: ShieldCheck,
    path: '/admin-mgmt/users',
    permission: PERMISSIONS.adminMgmt.view,
    subItems: [
      { id: 'admin-users', label: 'Admin Users', path: '/admin-mgmt/users', permission: PERMISSIONS.adminMgmt.view },
      { id: 'admin-roles', label: 'Roles', path: '/admin-mgmt/roles', permission: PERMISSIONS.adminMgmt.view },
      { id: 'admin-permissions', label: 'Permissions', path: '/admin-mgmt/permissions', permission: PERMISSIONS.adminMgmt.view },
      { id: 'admin-access-logs', label: 'Access Logs', path: '/admin-mgmt/access-logs', permission: PERMISSIONS.adminMgmt.view },
      { id: 'admin-activity-logs', label: 'Activity Logs', path: '/admin-mgmt/activity-logs', permission: PERMISSIONS.adminMgmt.view },
    ],
  },
];
