export const designTokens = {
  bg: 'var(--bg)',
  surface: 'var(--surface)',
  surfaceElevated: 'var(--surface-2)',
  mutedSurface: 'var(--muted-surface)',
  surfaceBright: 'var(--surface-bright)',
  border: 'var(--border)',
  glass: 'var(--glass)',
  text: 'var(--text)',
  textMuted: 'var(--text-muted)',
  brand: 'var(--brand)',
  brandStrong: 'var(--brand-strong)',
  primary: 'var(--brand)',
  positive: 'var(--positive)',
  negative: 'var(--negative)',
  warning: 'var(--warning)',
  accent: 'var(--accent)',
};
